###########################
# BUILD COMMANDS
###########################
[build]
  # command = ""
  # functions = "functions"
  publish = "."

[dev]
  # command = "" # Command to run when starting the dev server
  # port = 8888 # Port that the dev server will be accessible on
  publish = "." # Folder with the static content for _redirect file
  autoLaunch = true # Launches the local server address in your browser

###########################
# MAIN REDIRECTIONS
###########################
[[redirects]]
  from = "/favicon.ico"
  to = "https://jd.bruxelles.dev/favicon.ico"
  status = 301
  force = true
